[general]
import = [
    # "~/.config/alacritty/themes/nord.toml"
    # "~/.config/alacritty/catppuccin-latte.toml"
    # "~/.config/alacritty/catppuccin-frappe.toml"
    "~/.config/alacritty/catppuccin-macchiato.toml"
    # "~/.config/alacritty/themes/catppuccin-mocha.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
blur = true
opacity = 1
option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font"
normal.style = "Regular"
size = 14

[mouse]
hide_when_typing = true
